language: java

before_script:
  - chmod +x gradlew
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

jdk:
  - oraclejdk7
  - oraclejdk8

env:
 - GDX_VERSION=1.9.6

after_success:
  - gradlew desktop:dist
