language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

jdk:
  - oraclejdk7
  - oraclejdk8

env:
 - GDX_VERSION=1.9.5

after_success:
  - travis/jitpack-trigger.sh
