sudo: required

language: java

before_install:
 - chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

jdk:
  - oraclejdk7

env:
 - GDX_VERSION=1.9.6

after_success:
  - ./gradlew desktop:dist